### ISSUE TITLE
请问有deskmini 国外板已经改完的bios文件吗？

### ISSUE THREAD

**Issue by amoboy** [damnnfo/DeskMini-110-COM#1]
非com板

**Comment by damnnfo** [comment]
没有，你可以按教程自己做一个

**Comment by damnnfo** [comment]
好吧，发现以前改过，你到百度网盘里下载吧
路径>AMI BIOS>其它主板>其它华擎主板>H110M-STX

**Comment by amoboy** [comment]
大大,刚刚其实是找到了.但是并不确定..10分钟前翻了一下你的贴吧帖子,看到了...
还有一个问题问一下.因为你贴吧后面并没有在继续了.
1:就是不知道现在的7.3或者7.4的bios,如果按照你的方案应该也是可用的.不知道你是建议用7.2还是后面的bios.因为intel,熔断和幽灵bug.
2:没有6代或者7代的cpu.用编程器的话,文件是否也是用您网上留的那个.

**Comment by damnnfo** [comment]
1，用7.2的bios，cpu漏洞现在没有彻底修复问题的微码可用，me也不能升级11.8不然就不能用cfl。2，用编程器的话，刷不带np的rom。但个人建议还是借个U，进bios instant flash刷很快的，风险也低。
