### ISSUE TITLE
从你共享的 7.20 升级到 7.60，认不出PCIe 设备

### ISSUE THREAD

**Issue by no2key** [damnnfo/DeskMini-110-COM#4]
CPU: i3-8100，M.2 SSD: Samsung PM981. 

原本是 “H11STXC7.20np+gop1075+vbios1055.7z”， 升级到 “H11STXC7.60np+me116+vbios1058+gop1079.7z” 刷上去认不出 PCIe 的硬盘。 降级回  “H11STXC7.20np+gop1075+vbios1055.7z” 又好了。

**Comment by damnnfo** [comment]
我两台升级后都是正常用NVMe硬盘的，一个SM961，一个960evo；官方bios 7.60版更新含：在安装英特尔600p SSD时提高系统兼容性，不知道是否有影响
