### ISSUE TITLE
请问现在还有非com版的文件吗？

### ISSUE THREAD

**Issue by yuif37** [damnnfo/DeskMini-110-COM#7]
如题。在亚马逊上买的是无com版本的。我在网盘里也没有找到https://github.com/damnnfo/DeskMini-110-COM/issues/1 这里所提到的文件。
请问现在还提供非com版的bios文件吗？

**Comment by damnnfo** [comment]
以前有做旧版的H110M-STX，现在自己没去更新就删掉文件了。

**Comment by yuif37** [comment]
感谢。我自己已经做好了7.2的修改版bios，不过文件没有及时保存下来。
